spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/complaint_management?useSSL=false&serverTimezone=UTC
    username: complaint_user
    password: complaint_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: complaintManagementSecretKey2024
  expiration: 86400000

logging:
  level:
    com.municipality: DEBUG