version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: complaint-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: complaint_management
      MYSQL_USER: complaint_user
      MYSQL_PASSWORD: complaint_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - complaint-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    networks:
      - complaint-network

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    networks:
      - complaint-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - complaint-network

  complaint-service:
    build: ./complaint-service
    container_name: complaint-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
      - config-server
      - user-service
      - department-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - complaint-network

  department-service:
    build: ./department-service
    container_name: department-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - complaint-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - complaint-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - config-server
      - user-service
      - complaint-service
      - department-service
      - notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - complaint-network

volumes:
  mysql_data:

networks:
  complaint-network:
    driver: bridge